name: down2host

on:
  push:
    tags:
      - "host-v*.*.*"  # 后面每次更新提交，只有打上tag之后才会进行发布更新，减少actions执行次数
      - "v*.*.*"  # 后面每次更新提交，只有打上tag之后才会进行发布更新，减少actions执行次数
  workflow_dispatch:

jobs:
  job1:
    uses: spatxos/spatxos.github.io/.github/workflows/down-build.yml@host-v0.1.0
    secrets:
      cnblogsisdown: ${{ secrets.CNBLOGS_ISDOWN }}
      cnblogscookie: ${{ secrets.CNBLOGS_COOKIE }}
      blogname: ${{ secrets.BLOG_NAME }}

  # Host 自动部署
  down2host: 
    needs: [job1]
    name: Down 2 Host
    runs-on: ubuntu-latest
    steps:
      # get image tag name
      - name: Get Image Tag Name
        run: |
          if [ x${{ github.event.inputs.tag }} == x"" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器ip
          username: ${{ secrets.HOST_USERNAME }} # 服务器登录用户名
          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
          port: ${{ secrets.HOST_PORT }} # 服务器ssh端口
          script: |
            wget https://github.com/spatxos/spatxos.github.io/releases/download/${{env.TAG_NAME}}/${{secrets.BLOG_NAME}}.${{env.TAG_NAME}}.zip  --user-agent="Mozilla/5.0 (X11;U;Linux i686;en-US;rv:1.9.0.3) Geco/2008092416 Firefox/3.0.3" --no-check-certificate
            mkdir /root/${{secrets.BLOG_NAME}}-blog/html/
            unzip -d /root/${{secrets.BLOG_NAME}}-blog/html/ ${{secrets.BLOG_NAME}}.${{env.TAG_NAME}}.zip
            find . -name 'spatxos*v*.*.*.zip' | xargs rm